Add support for SRR of automatic groups
42ity/fty-automatic-group pull request #1
Opened 2021-02-24 00:51 UTC by stark-dev

Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>

2021-02-24 01:00 UTC, stark-dev commented
@etnKlendathu , @perrettecl please double check the control file ;)

2021-03-01 12:00 UTC, etnKlendathu requested changes
This is quite ok, but one big comment...
You did a job as not a job as others (other jobs are thread job, each routine pushed to the pool and server is free to accept other stuff). You did that all srr functions will block main server thread. I not sure if we want it.

2021-03-01 12:00 UTC, etnKlendathu commented on common/common/srr.h
> +    pack::ObjectList<Group> m_groupList = FIELD("groupList");
when you use pack struct you always use a field as getter/setter member.
srrgroup.groupList....
so, m_ prefix is somehow for private/protected members

2021-03-01 12:00 UTC, etnKlendathu commented on server/src/lib/server.cpp
> +    logDebug("Automatic group: got message {}", msg.dump());
:(

2021-03-04 12:30 UTC, etnKlendathu requested changes
quite ok :)
I mostly don't like to use append... you could add method to message setUserData() with clear call

2021-03-04 12:30 UTC, etnKlendathu commented on server/src/lib/task.h
> +                    if (m_in.userData[0].empty()) {
very risky... you should check that data have at least one element (!empty)

2021-03-04 12:30 UTC, etnKlendathu commented on server/src/lib/task.h
> +                msg.userData.append(*pack::json::serialize(out));
hmmm... to be honest, i don't like append here. What if some content already exists in data? Better to make replace here.

2021-03-04 12:30 UTC, etnKlendathu commented on server/src/lib/server.h
> +namespace messagebus {
I think you don't need it here already.

2021-03-05 07:09 UTC, merged