Add support group link
42ity/fty-automatic-group pull request #14
Opened 2021-03-11 17:25 UTC by yarovyii

Signed-off-by: Hlib Yarovyi <HlibYarovyi@eaton.com>

2021-03-11 18:09 UTC, perrettecl requested changes

2021-03-11 18:09 UTC, perrettecl commented on server/test/resolve.cpp
> +                    - type     : Server
Best will be to add another asset like "datacenter", and make sure that this one is not on the group, and also in group linked to the group.

2021-03-11 18:09 UTC, perrettecl commented on server/test/resolve.cpp
> +            cond1.op    = fty::Group::ConditionOp::Contains;
Better to check with IS and ISNOT. Contains do not make lot of sense for groups even if for this specific case IS == CONTAIN and ISNOT == DOESNOTCONTAIN

2021-03-16 11:17 UTC, etnKlendathu requested changes

2021-03-16 11:17 UTC, etnKlendathu commented on server/src/lib/jobs/resolve.cpp
> +        fty::implode(subQueries, ") " + sqlLogicalOperator(group.groupOp) + " id_asset_element " + strGroup + "IN ("));
Is not correct... 
if you have such case
```
conditions = [
{ field = Name, op = Is, value = srv },
{ field = Location, op = Is, value = datacenter },
{ field = Group, op = IsNot, value = 42 },
]
```
Then result query would be ```id in (select id where Name = srv) and not in (select id where location = datacenter) and not in (select if from group = 42```
So, you cannot to join subqueries in same negative condition from 1 subquery

2021-03-16 11:17 UTC, etnKlendathu commented on server/test/resolve.cpp
> +            auto g = group.create();
Please, create referenced group just ones before testing.

2021-03-16 11:17 UTC, etnKlendathu commented on server/test/resolve.cpp
> +            auto& var1  = group1.rules.conditions.append();
I know this is my sin too... but try to use meaning variables names, not var, var1, var2... in case if count of this more than 1 then begin mess...

2021-03-16 11:28 UTC, etnKlendathu commented
And please, in group creation add check on rules condition (limit operator on is, isnot if linked group)...

2021-03-16 11:56 UTC, etnKlendathu commented on server/test/resolve.cpp
> +            cond2.value = fty::convert<std::string, uint64_t>(g.id.value());
you do not need to specify second parameter here, bcoz autodeduction.

2021-03-18 15:56 UTC, etnKlendathu requested changes

2021-03-18 17:08 UTC, etnKlendathu requested changes

2021-03-18 17:08 UTC, etnKlendathu commented on server/src/lib/jobs/resolve.cpp
> +        for (auto query : subQueries) {
const auto&

2021-03-18 17:08 UTC, etnKlendathu commented on server/src/lib/jobs/resolve.cpp
> +        SubQuery(std::string q, std::string o = "IN")
const string&

2021-03-18 18:09 UTC, etnKlendathu requested changes
Now mostly unit tests, honestly to say, I don't like the linked group test... looks like mess.
Try to use json/yaml notification, maybe it will be more descriptive and easy to read.

2021-03-18 18:09 UTC, etnKlendathu commented on server/src/lib/jobs/resolve.cpp
> +    const auto & lambdaImplode = [&]() {
not here :)

2021-03-18 18:09 UTC, etnKlendathu commented on common/group.cpp
> +                return unexpected("Valid value of condition for linked group is expected"_tr);
Sorry, forgot to mention, add unit test for this in tests/create/update

2021-03-18 18:09 UTC, etnKlendathu commented on server/test/resolve.cpp
> +        auto g = group.create();
just 1 latter g? Please, try to use more :)
If you look to the other tests, you will find other way how to create group, try it, maybe json string will be more descriptive for you.

2021-03-25 18:40 UTC, etnKlendathu approved these changes

2021-07-29 07:22 UTC, merged